version: '3.1'
services:
  db:
    image: mysql:5
    command: --max_allowed_packet=20M
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./database/lobbywatch.sql:/docker-entrypoint-initdb.d/lobbywatch.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: public
  # admin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db:db
  #   ports:
  #     - 8080:80
  # ontop:
  #   image: ontop/ontop-endpoint:4.0-snapshot
  #   links:
  #     - db:db
  #   # ports:
  #   #   - 8080:8080
  #   volumes:
  #     - ./ontop-scripts/mysql-connector-java-5.1.49/:/opt/ontop/jdbc
  #     - ./ontop-scripts/ontop-entrypoint.sh:/opt/ontop/entrypoint.sh
  #     - ./ontop-scripts:/opt/ontop/output
  #     - ./src-gen:/static
  #   environment:
  #     - ONTOP_MAPPING_FILE=/static/lobbywatch-mapping.r2rml.ttl
  #     - ONTOP_PROPERTIES_FILE=/static/ontop.mysql.properties
