apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lod-lobbywatch-ch

commonLabels:
  app.kubernetes.io/instance: lod.lobbywatch.ch
  app.kubernetes.io/name: trifid

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
