PREFIX schema: <http://schema.org/>

DELETE {
  GRAPH <https://lod.lobbywatch.ch> {
    <https://lod.lobbywatch.ch/committee/bu-vbv-v> ?p ?o.
  }
}
INSERT {
  GRAPH <https://lod.lobbywatch.ch> {
    <https://politics.ld.admin.ch/council/committee/708> ?p_new ?o_new.
    <https://politics.ld.admin.ch/council/committee/708> ?p ?o.
  }
}
WHERE {
  GRAPH <https://lod.lobbywatch.ch> {

    <https://lod.lobbywatch.ch/committee/bu-vbv-v> ?p ?o.


  SERVICE <https://test.lindas.admin.ch/query> {
    GRAPH <https://lindas.admin.ch/fch/curia> {
      <https://politics.ld.admin.ch/council/committee/708> ?p_new ?o_new.
    }
  }
}
}
