PREFIX schema: <http://schema.org/>

DELETE {
  GRAPH <https://lod.lobbywatch.ch> {
    ?committee_orig ?p ?o.
  }
}
INSERT {
  GRAPH <https://lod.lobbywatch.ch> {
    ?committee_lindas ?p ?o.
  }
}
WHERE {
  GRAPH <https://lod.lobbywatch.ch>{
	{?committee_orig a <https://paf.link/Committee>;
      schema:memberOf <https://politics.ld.admin.ch/council/N>;
      schema:alternateName ?abb;
    ?p ?o.

  FILTER (LANG(?abb) = "de")
  SERVICE <https://test.lindas.admin.ch/query> {
    GRAPH <https://lindas.admin.ch/fch/curia> {
      ?committee_lindas schema:memberOf <https://politics.ld.admin.ch/council/N>;
      schema:alternateName ?abb.
    }
  }} UNION {
    ?committee_orig a <https://paf.link/Committee>;
      schema:memberOf <https://politics.ld.admin.ch/council/S>;
      schema:alternateName ?abb;
    ?p ?o.

  FILTER (LANG(?abb) = "de")
  SERVICE <https://test.lindas.admin.ch/query> {
    GRAPH <https://lindas.admin.ch/fch/curia> {
      ?committee_lindas schema:memberOf <https://politics.ld.admin.ch/council/S>;
      schema:alternateName ?abb.
    }
  }
  }
  }
}
