PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH <https://lod.lobbywatch.ch> {
    ?faction_old ?p_outwards ?o.

  }
}
INSERT {
  GRAPH <https://lod.lobbywatch.ch> {
    ?faction_lindas ?p_outwards ?o.
    ?faction_lindas ?p_outwards_new ?o_new.
  }
}
WHERE {
  GRAPH <https://lod.lobbywatch.ch> {

   ?faction_old a <http://schema.org/ParliamentaryGroup>;
    <http://schema.org/alternateName> ?abb_lindas;
    ?p_outwards ?o.

  SERVICE <https://lindas.admin.ch/query> {
    GRAPH <https://lindas.admin.ch/fch/curia> {

      ?faction_lindas a <http://schema.org/ParliamentaryGroup>;
    	<http://schema.org/alternateName> ?abb_lindas.

      FILTER (LANG(?abb_lindas) = "de")
    }
  }
  }
}

