PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH <https://lod.lobbywatch.ch> {
    ?s ?p_inwards ?faction_old.

  }
}
INSERT {
  GRAPH <https://lod.lobbywatch.ch> {
    ?s ?p_inwards ?faction_lindas.
  }
}
WHERE {
  GRAPH <https://lod.lobbywatch.ch> {

  ?faction_old a <https://paf.link/Faction>;
    <https://paf.link/hasAbbreviation> ?abb_lindas.

  ?s ?p_inwards ?faction_old.

  SERVICE <https://test.lindas.admin.ch/query> {
    GRAPH <https://lindas.admin.ch/fch/curia> {

      ?faction_lindas a <http://schema.org/Organization>;
    	<https://paf.link/isActive> ?active;
    	<https://paf.link/hasAbbreviation> ?abb_lindas.

      FILTER (LANG(?abb_lindas) = "de")
    }
  }
  }
}

