PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {
  GRAPH <https://lod.lobbywatch.ch> {
      <https://politics.ld.admin.ch/council/N> a <http://dbpedia.org/ontology/Parliament>;
              a <https://paf.link/Council>;
              owl:sameAs <https://www.wikidata.org/wiki/Q676078>.
      <https://politics.ld.admin.ch/council/S> a <http://dbpedia.org/ontology/Parliament>;
              a <https://paf.link/Council>;
              owl:sameAs <https://www.wikidata.org/wiki/Q609037>.
      <https://politics.ld.admin.ch/council/FA> a <http://dbpedia.org/ontology/Parliament>;
              owl:sameAs <https://www.wikidata.org/wiki/Q684719>.
  }
}

