INSERT {
  ?lwPerson <http://schema.org/sameAs> ?wikidataPerson .
}
WHERE {
  ?lwPerson a <http://dbpedia.org/ontology/MemberOfParliament> ;
            <http://www.wikidata.org/prop/direct/P1307> ?parliamentId .
  BIND (STR(?parliamentId) AS ?pid)

  SERVICE <https://query.wikidata.org/sparql> {
    ?wikidataPerson <http://www.wikidata.org/prop/direct/P1307> ?pid .
  }
}
