name: Lobbywatch R2RML Workflow

on:
  schedule:
    - cron: "0 0 1,15 * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STARDOG_AUTH: ${{ secrets.STARDOG_AUTH }}

    steps:
    - uses: actions/checkout@v2
    - name: Install NPM pipeline
      run: cd pipeline && npm ci
    - name: Run the whole project
      run: |
        make sql convert
        cd ontop-scripts
        echo "Hello"
        echo "$ENDPOINT"
        curl -v \
            -X PUT \
            --header "Authorization: Basic $STARDOG_AUTH" \
            --header "Content-Type:application/n-triples; charset=utf-8" \
            -T ./triples-slug.nt \
            --data-urlencode graph=https://lod.lobbywatch.ch \
            -G $ENDPOINT
