name: Lobbywatch R2RML Workflow

on:
  schedule:
    - cron: "0 0 1,15 * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STARDOG_AUTH: ${{ secrets.STARDOG_AUTH }}

    steps:
    - uses: actions/checkout@v2
    - name: Install NPM pipeline
      run: cd pipeline && npm ci
    - name: Run the whole project
      run:
        - cd database && docker-compose stop db
	      - cd database && ./get-dump.sh
	      - cd database && docker-compose up -d db
	      - sleep 20
	      - mysql -h 127.0.0.1 -u root --database lobbywatch_public --password=public < database/wirksamkeit.sql
        - cd ontop-scripts && ./1-convert.sh
        - cd ontop-scripts && ./2-upload.sh
